-- 코드를 작성해주세요
SELECT A.ID, A.GENOTYPE, B.GENOTYPE AS PARENT_GENOTYPE FROM ECOLI_DATA A JOIN (
SELECT DISTINCT ID, GENOTYPE FROM ECOLI_DATA WHERE ID IN (SELECT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)) B ON A.PARENT_ID=B.ID AND A.GENOTYPE&B.GENOTYPE=B.GENOTYPE ORDER BY A.ID ASC;